export const skills = [
    "semantic & accesible HTML",
    "Responsive Web Desing",
    "Teamwork",
    "Markdown",
    "Immutability",
    "CSS BEM Convention",
    "CSS Grid",
    "CSS Flexbox",
    "React Router",
    "Redux - Saga",
    "Redux (Toolkit)",
    "React Hooks",
    "Error handling",
    "Working with APi (fetch,axios)",
    "Javascript: ES6+",
    "Promise, Async/Await",
    "GitHub Pull request & Review",
    "Trello",
    "Scrum",
    "NPM",
    "React",
    "Git",
];

export const skillsToLearn = [
    "React Context",
    "Node.js",
    "TypeScript",
    "Unit testing",
];