const colors = {
    black: "#000000",
    mineShaft: "#252525",
    semiGray: "rgba(54, 54, 54, 0.72)",
    slateGray: "#6E7E91",
    scienceBlue: "#0366D6",
    dodgerBlue: "#2188FF",
    whiteLiliac: "#FBFBFE",
    white: "#FFFFFF",
    iron: "#D1D5DA;",
    anakiwa: "#8CC2FF",
    dustyGray: "#d1d5da",
    lightBlue: "rgba(3, 102, 214, 0.20)"
}
const breakpoints = {
    smallPhone: 365,
    phone: 767,
    tablet: 934,
    smallLaptop: 1200,
    laptop: 1400,
}

export const themeLight = {
    color: {
        mainBackground: colors.whiteLiliac,
        title: colors.black,
        paragraph: colors.slateGray,
        description: colors.slateGray,
        buttonColor: colors.white,
        buttonBackground: colors.scienceBlue,
        themeText: colors.slateGray,
        themeBorderButton: colors.slateGray,
        themeIcon: colors.white,
        themeIconWrapper: colors.slateGray,
        themeBacgkround: colors.iron,
        sectionTitle: colors.mineShaft,
        sectionTitleBorder: colors.iron,
        sectionBackground: colors.white,
        listItem: colors.slateGray,
        listOrder: colors.scienceBlue,
        portfolioItemBackground: colors.white,
        portfolioItemTitle: colors.scienceBlue,
        portfolioItemDescription: colors.slateGray,
        portfolioLink: colors.scienceBlue,
        footerBackground: colors.whiteLiliac,
        footerLink: colors.black,
        footerLinkActive: colors.scienceBlue,
        footerEmail: colors.black,
        emailHover: colors.scienceBlue,
        error: colors.black,
        errorButton: colors.scienceBlue,
    },
    breakpoints: {
        smallPhone: breakpoints.smallPhone,
        phone: breakpoints.phone,
        tablet: breakpoints.tablet,
        smallLaptop: breakpoints.smallLaptop,
        laptop: breakpoints.laptop,
    },
};

export const themeDark = {
    color: {
        mainBackground: colors.mineShaft,
        title: colors.white,
        paragraph: colors.white,
        description: colors.white,
        buttonColor: colors.white,
        buttonBackground: colors.dodgerBlue,
        themeText: colors.white,
        themeBorderButton: colors.white,
        themeIcon: colors.mineShaft,
        themeIconWrapper: colors.white,
        themeBackground: colors.semiGray,
        sectionTitle: colors.white,
        sectionTitleBorder: colors.semiGray,
        sectionBackground: colors.semiGray,
        listItem: colors.white,
        listOrder: colors.dodgerBlue,
        portfolioItemBackground: colors.semiGray,
        portfolioItemTitle: colors.white,
        portfolioItemDescription: colors.white,
        portfolioLink: colors.scienceBlue,
        footerBackground: colors.mineShaft,
        footerLink: colors.white,
        footerLinkActive: colors.scienceBlue,
        footerEmail: colors.white,
        emailHover: colors.scienceBlue,
        error: colors.white,
        errorButton: colors.scienceBlue,
    },
    breakpoints: {
        smallPhone: breakpoints.smallPhone,
        phone: breakpoints.phone,
        tablet: breakpoints.tablet,
        smallLaptop: breakpoints.smallLaptop,
        laptop: breakpoints.laptop,
    },
};